<div class="tcb-tabs-container">
	<div class="tcb-header-tabs">
		<div class="tab-item" data-content="symbol" data-tab="symbol"><?php echo __( 'Symbols', 'thrive-cb' ); ?></div>
		<div class="tab-item active" data-content="ct" data-tab="templates"><?php echo __( 'Content Templates', 'thrive-cb' ); ?></div>
	</div>
	<div class="tabs-content">
		<div class="tcb-tab-content symbols-content" data-content="symbol"></div>
		<div class="tcb-tab-content ct-content active" data-content="ct"></div>
	</div>
</div>
